Repository MultiProject23/React-Project, pull requests merged in 2023-03, with the labels that each got.

#4 [FE] Routes 기능 추가
  src/App.jsx
  src/index.jsx
  src/pages/Cart/index.jsx
  src/pages/Details/index.jsx
  src/pages/Join/index.jsx
  src/pages/Login/index.jsx
  src/pages/Main/index.jsx
  src/pages/Outfit/index.jsx
  src/pages/Review/index.jsx
  src/routes/index.jsx
Labels: 🚀 feature

#7 [FE] 외부 여백 제거
  src/App.jsx
  src/app.styled.js
  src/index.jsx
  src/styles/App.css
  src/styles/index.css
Labels: 🖼️ UI, 🔧 fix

#9 [FE] Not Found 페이지 구현
  src/assets/NotFound/pic.png
  src/assets/logo.svg
  src/components/FontAwesome/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/NotFound/index.styled.js
  src/routes/index.jsx
Labels: 🖼️ UI, 🚀 feature

#10 [FE] Footer - react-router-dom Link 기능 구현
  src/components/Footer/index.jsx
  src/components/Footer/index.styled.js
  src/components/Header/Nav/index.jsx
Labels: 🚀 feature, 🔧 fix

#12 [FE] ScrollToTop 기능 구현
  src/App.jsx
  src/components/ScrollToTop/index.jsx
Labels: 🚀 feature

#13 [FE] React.Lazy, Suspense 기능 추가
  src/App.jsx
  src/components/Loading/Animation/index.jsx
  src/components/Loading/Animation/style.css
  src/components/Loading/index.jsx
  src/components/Loading/index.styled.js
  src/pages/index.jsx
  src/routes/index.jsx
Labels: 🖼️ UI, 🚀 feature

#16 [FE] PageLayout - 하단 공백이 생기는 버그 해결
  src/assets/Banner/banner.jpg
  src/components/Banner/index.jsx
  src/components/Banner/index.styled.js
  src/components/Footer/index.styled.js
  src/layouts/pages/index.styled.js
  src/pages/Main/index.jsx
Labels: ❌ bug, 🖼️ UI

#19 docs: Update Readme
  README.md
Labels: 📖 docs

#22 [FE] Main - Card UI/UX 구현
  src/assets/Card/kids.png
  src/assets/Card/men.png
  src/assets/Card/space.png
  src/assets/Card/women.png
  src/components/Card/index.jsx
  src/components/Card/index.styled.js
  src/pages/Main/Cards/index.jsx
  src/pages/Main/Cards/index.styled.js
  src/pages/Main/index.jsx
Labels: 🖼️ UI, 🚀 feature

#21 [Docs] Update FE Readme
  README.md
Labels: 📖 docs

#24 [FE] Footer - Content 폴더 삭제
  src/components/Footer/Content/index.jsx
  src/components/Footer/Content/index.styled.js
Labels: 🎨 refactor

#27 [FE] Main - Category UI/UX 수정
  src/components/Category/index.styled.js
Labels: 🖼️ UI, 🔧 fix

#28 [FE] Main - TextSection
  src/pages/Main/Text/index.jsx
  src/pages/Main/Text/index.styled.js
  src/pages/Main/index.jsx
Labels: 🖼️ UI

#31 [FE] Header Link 추가
  src/components/Header/Nav/index.jsx
  src/components/Header/Nav/index.styled.js
  src/components/Header/User/index.jsx
  src/components/Header/User/index.styled.js
  src/pages/My/index.jsx
  src/pages/Product/index.jsx
  src/pages/index.jsx
  src/routes/index.jsx
Labels: 🚀 feature

#33 [FE] MyPage 구현
  src/pages/My/Orders/Row/index.jsx
  src/pages/My/Orders/Row/index.styled.js
  src/pages/My/Orders/index.jsx
  src/pages/My/Orders/index.styled.js
  src/pages/My/Profile/index.jsx
  src/pages/My/Profile/index.styled.js
  src/pages/My/index.jsx
  src/pages/My/index.styled.js
Labels: 🖼️ UI, 🚀 feature

#39 [FE] 상품상세페이지 라우터 설정
  src/routes/index.jsx
Labels: 🚀 feature

#41 [FE] [이진영] Product Page UI 구현
  public/img/03.jpg
  public/img/04.jpg
  public/img/05.jpg
  public/img/06.jpg
  public/img/07.jpg
  public/img/08.jpg
  public/img/09.jpg
  public/img/10.jpg
  public/img/11.jpg
  public/img/12.jpg
  public/img/13.jpg
  public/img/14.jpg
  public/img/15.jpg
  public/img/16.jpg
  public/img/17.jpg
  public/img/18.jpg
  public/img/19.jpg
  public/img/20.jpg
  public/img/23.jpg
  public/img/24.jpg
  src/pages/Product/index.jsx
  src/pages/Product/index.styled.css
Labels: 🖼️ UI

#35 [FE] Details Page 구현
  package.json
  src/assets/Details/c1.jpg
  src/assets/Details/c2.jpg
  src/assets/Details/c3.jpg
  src/assets/Details/c4.jpg
  src/assets/Details/c5.jpg
  src/assets/Details/coat1.jpg
  src/assets/Details/coat2.jpg
  src/assets/Details/coat3.jpg
  src/assets/Details/coat4.jpg
  src/assets/Details/coat5.jpg
  src/assets/Details/coat6.jpg
  src/assets/Details/coat7.jpg
  src/assets/Details/coat8.jpg
  src/pages/Details/carousel/SimpleSlider.jsx
  src/pages/Details/index.jsx
  src/pages/Details/info/Content.jsx
  src/pages/Details/info/LinkMenu.jsx
  src/pages/Details/info/MaterialTable.jsx
  src/pages/Details/info/MenuTabs.jsx
  src/pages/Details/info/RelatedProduct.jsx
  src/pages/Details/info/SizeTable.jsx
  src/pages/Details/order/CartButton.jsx
  src/pages/Details/order/DeliveryButton.jsx
  src/pages/Details/order/OrderContainer.jsx
  src/pages/Details/order/SizeButton.jsx
  src/pages/Details/order/SizeCheck.jsx
  src/pages/Details/order/SizeModal.jsx
  src/pages/Details/order/StockButton.jsx
  yarn.lock
Labels: 🖼️ UI, 🚀 feature

#36 [FE] Login,Join Page 구현
  src/pages/Join/index.jsx
  src/pages/Join/index.styled.css
  src/pages/Login/index.jsx
  src/pages/Login/index.styled.css
Labels: 🖼️ UI, 🚀 feature

#42 [FE] 파일 구조 변경
  src/pages/Details/order/SizeButton/index.styled.js
  src/styles/fonts.jsx
Labels: 🖼️ UI

#43 [FE] Cart UI 구현
  src/pages/Cart/Image/image001.png
  src/pages/Cart/Image/image002.png
  src/pages/Cart/Image/image003.png
  src/pages/Cart/Image/image004.png
  src/pages/Cart/Image/image005.png
  src/pages/Cart/Image/image006.png
  src/pages/Cart/Row/index.jsx
  src/pages/Cart/Row/index.styled.js
  src/pages/Cart/index.jsx
  src/pages/Cart/index.styled.js
  src/pages/Details/info/LinkMenu/index.styled.js
  src/pages/Details/order/SizeModal.jsx
Labels: 🖼️ UI

#60 [FE] Product 기능 구현
  src/components/Product/Card/index.jsx
  src/components/Product/Card/index.styled.css
  src/components/Product/Nav/index.jsx
  src/components/Product/Nav/index.styled.js
  src/components/Product/NotFound/index.jsx
  src/components/Product/NotFound/index.styled.js
  src/data/product/data.json
  src/pages/Product/index.jsx
  src/pages/Product/index.styled.css
  src/styles/fonts.jsx
Labels: 🖼️ UI, 🚀 feature

#62 [FE] MyPage 수정
  src/components/Header/User/index.jsx
  src/components/My/Address/ChangeForm/index.jsx
  src/components/My/Address/ChangeForm/index.styled.js
  src/components/My/Address/index.jsx
  src/components/My/Address/index.styled.js
  src/components/My/NotFound/index.jsx
  src/components/My/NotFound/index.styled.js
  src/components/My/Orders/Row/index.jsx
  src/components/My/Orders/Row/index.styled.js
  src/components/My/Orders/index.jsx
  src/components/My/Orders/index.styled.js
  src/components/My/Output/index.jsx
  src/components/My/Output/index.styled.js
  src/components/My/Profile/ChangeForm/index.jsx
  src/components/My/Profile/ChangeForm/index.styled.js
  src/components/My/Profile/index.jsx
  src/components/My/Profile/index.styled.js
  src/data/MyPage/data.json
  src/pages/My/Address/index.jsx
  src/pages/My/Orders/index.jsx
  src/pages/My/Profile/index.jsx
  src/pages/My/index.jsx
  src/pages/My/index.styled.js
Labels: 🖼️ UI, 🚀 feature

#64 [FE] Main Page 수정
  src/assets/Category/bag.jpg
  src/assets/Category/bag2.jpg
  src/assets/Category/basic.jpg
  src/assets/Category/basic2.jpg
  src/assets/Category/hat.jpg
  src/assets/Category/hat2.jpg
  src/assets/Category/image.js
  src/assets/Category/outer.jpg
  src/assets/Category/outer2.jpg
  src/assets/Category/pant.jpg
  src/assets/Category/pant2.jpg
  src/assets/Category/shoes.jpg
  src/assets/Category/shoes2.jpg
  src/assets/Category/top.png
  src/assets/Category/top2.jpg
  src/assets/Category/total.jpg
  src/assets/Category/total2.jpg
  src/assets/Category/women.jpg
  src/components/Banner/index.jsx
  src/components/Category/index.jsx
  src/components/Category/index.styled.js
  src/pages/Main/Cards/index.jsx
Labels: 🚀 feature, 🔧 fix, 🎨 refactor

#67 [FE] Footer 디자인 수정
  src/components/Footer/index.styled.js
Labels: 🖼️ UI

#68 [FE] Footer의 디자인 수정
  src/components/Footer/index.styled.js
Labels: 🖼️ UI, 🔧 fix

#63 [FE] Product 페이지 수정
  src/components/FilterNav/index.jsx
  src/components/FilterNav/index.styled.js
  src/components/Product/Nav/index.jsx
  src/components/Product/Nav/index.styled.js
  src/constants/category.js
  src/data/product/data.json
  src/pages/Product/index.jsx
  src/pages/Product/index.styled.css
Labels: 🖼️ UI, 🚀 feature

#65 [FE] Header 수정
  src/components/Header/User/index.jsx
  src/components/Header/User/index.styled.js
  src/data/data.json
Labels: 🖼️ UI, 🚀 feature

#61 [FE] Cart 수정
  src/components/Cart/NotFound/index.jsx
  src/components/Cart/NotFound/index.styled.js
  src/components/Cart/Row/index.jsx
  src/components/Cart/Row/index.styled.js
  src/data/Cart/data.json
  src/pages/Cart/Image/image001.png
  src/pages/Cart/Image/image002.png
  src/pages/Cart/Image/image003.png
  src/pages/Cart/Image/image004.png
  src/pages/Cart/Image/image005.png
  src/pages/Cart/Image/image006.png
  src/pages/Cart/Row/index.jsx
  src/pages/Cart/Row/index.styled.js
  src/pages/Cart/index.jsx
  src/pages/Cart/index.styled.js
  src/pages/Product/index.jsx
Labels: 🖼️ UI, 🚀 feature

#71 [FE] MyPage Axios 기능 구현
  src/components/Cart/Row/index.jsx
  src/components/Header/User/index.jsx
  src/components/My/Address/ChangeForm/index.jsx
  src/components/My/Address/ChangeForm/index.styled.js
  src/components/My/Address/index.jsx
  src/components/My/Orders/Row/index.jsx
  src/components/My/Profile/ChangeForm/index.jsx
  src/components/My/Profile/ChangeForm/index.styled.js
  src/components/My/Profile/index.jsx
  src/constants/message.js
  src/constants/path.js
  src/constants/rule.js
  src/data/Cart/data.json
  src/data/Header/data.json
  src/data/MyPage/data.json
  src/data/data.json
  src/pages/My/index.jsx
  src/pages/Product/index.jsx
  src/routes/index.jsx
  src/utils/validate.js
Labels: 🚀 feature, 🎨 refactor

#66 [FE] review 수정
  public/img/ReviewTest_1.jpg
  public/img/ReviewTest_2.jpg
  public/img/ReviewTest_3.jpg
  public/img/ReviewTest_4.jpg
  public/img/ReviewTest_5.jpg
  public/img/ReviewTest_6.jpg
  public/img/ReviewTest_7.jpg
  public/img/ReviewTest_8.jpg
  src/assets/Review/profile.jpg
  src/assets/Review/reviewData.json
  src/components/Review/ReviewContent/index.jsx
  src/components/Review/ReviewContent/index.styled.js
  src/components/Review/ReviewFoot/index.jsx
  src/components/Review/ReviewModal/index.jsx
  src/components/Review/ReviewModal/index.styled.js
  src/components/Review/ReviewPagenation/index.jsx
  src/components/Review/ReviewPagenation/index.styled.js
  src/components/Review/ReviewSearch/index.styled.js
  src/components/Review/index.jsx
  src/components/Review/index.styled.js
Labels: 🚀 feature, 🎨 refactor

#73 [FE] login,join페이지 수정
  src/pages/Join/Birth.jsx
  src/pages/Join/Email.jsx
  src/pages/Join/Name.jsx
  src/pages/Join/Phone.jsx
  src/pages/Join/Pw.jsx
  src/pages/Join/PwCheck.jsx
  src/pages/Join/RegisterForm.jsx
  src/pages/Join/index.jsx
  src/pages/Join/index.styled.css
  src/pages/Login/EmailInput.jsx
  src/pages/Login/LoginForm.jsx
  src/pages/Login/PwInput.jsx
  src/pages/Login/index.jsx
  src/pages/Login/index.styled.css
Labels: 🖼️ UI, 🚀 feature, 🎨 refactor
